### ISSUE TITLE
Beta Expiration 

### ISSUE THREAD

**Issue by agautsc** [codeforgreenville/trolley-tracker-ios-client#10]
@austin9350 

@bikeoid and met with Greenlink this morning. Kathy from Greenlink opened her app at the meeting and said something like "Beta Period Expired" We believe she needed to update the app, but wanted to check and make sure we don't need to email the iOS beta testers to let them know about a potential expiration.

**Comment by austin9350** [comment]
You’re correct, there is a newer build available that is still valid for another two weeks. She should be able to update it through the TestFlight app.
Also, I’m fixing a few last little things tonight and hopefully will be uploading a new build for beta testers that I will also submit for public App Store review. 
Are there any concerns or open issues on the backend side that need to be resolved before a public release?

**Comment by jeremywight** [comment]
I think the only things we wanted to mainly improve were notifications to
the user when the trolley isn't running, but overall it has seemed to be
pretty stable. Agreed @agautsc?

**Comment by austin9350** [comment]
This new build lets users see the schedules, sorted by route or by day, and when there are no trolleys running shows a notice telling users they can check the schedules.

**Comment by agautsc** [comment]
There are some connection issues mainly around figuring out how to report if the trolley tablet isn't turned on or if the internet is down that we're looking in to. @bikeoid how long do you think the warning that both trolleys aren't online will take?

If you're comfortable taking it out of beta I think it would be fine. We have 133 iOS beta folks right now. I'm not sure how the beta process works but it seems like Apple wants to get you out of Beta quickly.

**Comment by bikeoid** [comment]
I hope to get the warning system finished this weekend.  I'll have it text me first, and later on will add Steve to the list and anyone else can subscribe also later.

It would be good to leave the beta process because others will probably be getting the expired app.  But we really need to revisit the Hot Spot on the trolley:
  * Last night both units started properly.
  * Later, one dropped off and the other was on a delayed beacon.
  * I texted Steve, and eventually both units returned to operation.    

  The Internet doesn't seem right, and we will need to do something to ensure that we meet reasonable rider expectations.   Possible solutions?
 * Assuming this hotspot is 2G or 3G, replace with a 4G Hot Spot?
 * Are tablet updates bogging down the connection?
 * Do we need a different type of Hot Spot with a better antenna for reception?
 * Change tablet to one with integrated Internet, or just go with our own phone but use Greenlink's data plan?

**Comment by ajhodges** [comment]
It did seem like the hotspot used in the tablet must have been 3G. It took us FOREVER to update the trolleys. I'm hesitant to suggest replacing the modems because I've been pretty content with treating that as a "black box", and want to stay out of Rick's hair.

Having said that, it is becoming clear that the connectivity actually is an issue (and it's not just operator error). The cleanest sounding solution (from my perspective) would be to replace the tablets with their respective LTE version, which is the Samsung SM-T337V (Galaxy Tab 8 4G, Verizon version). Then swap the verizon modem sim cards for ones for the tablets, and ensure the service contract includes 4G.

I guess that's only possible if we know for sure the trolley wifi isn't being used for anything else.

**Comment by agautsc** [comment]
I think it's going to be fairly tough to talk Greenlink into putting more cash into things like modems and tablets. However, I think the best way to make that happen would be report that shows wi-fi issues. Does anyone know of an Android app that show a report on wi-fi connections / uptime? OrangeCoat uses http://www.monitis.com/ to check for website uptime. @allella could Monitis be used to check and see if an individual tablet or application is connected to the internet?

**Comment by greenlinktransit** [comment]
Just an FYI -- we have yet to pay RouteMatch for the Samsung tablets. It's a little confusing, but in January we requested that RouteMatch equip our Trolleys with their hardware (terrible move, I know).  They delivered and installed the equipment, but failed to get the software up and running before we called it quits with them.  That hardware, and some other hardware that they delivered to us in the spring, is a hot topic among our Board.  We are hopeful that we can return that equipment to RouteMatch without paying for it and without having to pursue legal action.

That being said, we could very well return the tablets and purchase something different (with approval from the Board).  As for timing, I have no idea when that would happen.

**Comment by greenlinktransit** [comment]
Trolley #1 was showing up during Lunchlink this morning but it has since disappeared.  We're checking with John, our driver, to make sure that the tablet is on, but I can almost assure you that it is (John is good about turning it on).

Once I confirm that it is on, I'll try to get our IT staff to go check the internet connection.  I'm starting to think that it might have something to do with Cradlepoint's WiFi management.  We've had crazy overages during the last couple months, so they are now managing it so it can be throttled back when we approach out limit.  

Anyway, I'll let everyone know once I have an update.

**Comment by ajhodges** [comment]
So it sounds like our trolley WiFi is a ticking time bomb anyways? As I
understand it, the trolley routers and modems were part of that routematch
equipment package. Are the tablet mounts part of that deal too?

We might should look at getting our own tablet(lte capable)/mount combo
then. I'm sure we could work out a low cost solution..

Just an FYI -- we have yet to pay RouteMatch for the Samsung tablets. It's
a little confusing, but in January we requested that RouteMatch equip our
Trolleys with their hardware (terrible move, I know). They delivered and
installed the equipment, but failed to get the software up and running
before we called it quits with them. That hardware, and some other hardware
that they delivered to us in the spring, is a hot topic among our Board. We
are hopeful that we can return that equipment to RouteMatch without paying
for it and without having to pursue legal action.

That being said, we could very well return the tablets and purchase
something different (with approval from the Board). As for timing, I have
no idea when that would happen.

—
Reply to this email directly or view it on GitHub
<https://github.com/codeforgreenville/trolley-tracker-ios-client/issues/10#issuecomment-152567317>
.

**Comment by greenlinktransit** [comment]
Re: Adam's last comment....I wouldn't say it's a ticking time bomb.  Yes, the tablet mount is RouteMatch's but the modem is ours.  It was my intention to return all of our hardware to Routematch with the exception of the two Samsung tablets and their mounts (we would pay RouteMatch for those in order to keep the Trolley Tracker running).  If you guys are telling me that we can and should use something different, then I think it's in everyone's best interest to return the hardware and get something else.  For what it's worth, they are asking for $1,360 for the 2 tablets, chargers, and mounts.  I have a feeling we can get something more suitable for a lower cost.

Also, just a heads up that I intercepted the trolley and I think I diagnosed the problem.  Trolley #1 was attempting to connect to the City of Greenville's wifi rather than the MobilLinQ wifi, which is on the vehicle.  When I connected to MobilLinQ, the vehicle instantly showed up on the app.  I went into the tablet's setting to make sure that MobilLinQ is set to connect automatically.

**Comment by ajhodges** [comment]
Wow, thanks for intercepting that trolley! Appreciate the leg work. That
tells me that we need to make sure the tablets don't have any saved access
points other than the MobiLinQ one and are configured to not attempt to
connect to public wifi. I wonder how many of our issues that has caused.
Didn't even think about that.

As for the tablets.... we could get used ones for ~$150 or new for <$300. I
can't imagine high quality mounts costing more than $60. I guess the
downside of sourcing our own would be some downtime while the tablets are
procured?

Here's some refurb ones that are identical to the routematch ones (save for
LTE compatibility)
http://smile.amazon.com/Samsung-Galaxy-Tablet-8-Inch-16GB/dp/B00ZG2DOLO/ref=sr_1_9?s=pc&ie=UTF8&qid=1446230984&sr=1-9&keywords=tablet+verizon

**Comment by greenlinktransit** [comment]
No problem, glad to help.  As for the new tablets....we do not have to procure anything under $1,500, so we could go buy new ones today (in theory).  However, to do that we will need our legal counsel and RouteMatch to agree on a no-cost return.  For now, we'll keep the tablets as-is, but if we negotiate the return, let's huddle up to identify a product that's cost effective and suits your needs.

**Comment by bikeoid** [comment]
Fantastic!  That would certainly explain many of the inconsistencies we've seen, and there's a good chance that this will move it to a public announcement quality.

Is there a way to "forget a Wifi connection" as well?   I've seen my phone try to bounce around and try anything it knows about if one link goes down.   We would not want the tablet to try the city Wifi when the Verizon modem is still coming online.

**Comment by greenlinktransit** [comment]
I actually tried removing the other connections but wasn't successful.  I'll try again this weekend or next week.

**Comment by jeremywight** [comment]
Agreed. Great find! If we clear out all the other access points it won't
try to connect to those. Probably worth watching that and seeing if it
solves the issues.

**Comment by bikeoid** [comment]
Report from Friday night:

   Started with trolley 5 only, texted Steve at about 6:30, (Steve responded that Trolley 6 driver was delayed in starting due to an accident).
  Trolley 6 eventually showed up, but the beacon stalled about 1/2 hour later just after it reached Academy St - it reappeared after another 1/2 hour running the rest of the route at hyper-speed.    I don't think the city WiFi reaches anywhere near the intersection of Wardlaw / 123 (tonight's detour) where it stalled out.
  Later, Trolley 6 dropped off, then Trolley 5 stopped transmitting at about 9:30, and it was not in the "trolley barn" at that time, but on River Street.

   There may still be some more tuning that we can do to improve the Internet, but I think we should pursue the alternate Internet via Tablet solution.

I've got the pager application ready, but won't set it to text Steve directly yet - too many nuisance pages - there would have been 3 pages tonight but one actual incident (late trolley).

**Comment by agautsc** [comment]
@greenlinktransit the only way I know to remove wireless connection is to "Forget" a network by long pressing on a Wifi location http://www.androidcentral.com/android-101-how-forget-wifi-network

We should probably do a little more research into Android apps to manage wifi more completely. I bet there something out there that would allow us to define a single SSID or IP to connect to and so on and so forth. Maybe something like https://play.google.com/store/apps/details?id=app.com.superwifi
