### ISSUE TITLE
Trolley Not showing routes

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-ios-client#29]
@austin9350 it seems that now that @bikeoid has added the route timing to the JSON response, the app is not displaying the routes at all. It's working in the web app and in Android, however iOS doesn't show it for some reason.

**Comment by jeremywight** [comment]
Not sure if the code on Github is up to date, but it appears that it's pointing to the old URL: https://github.com/codeforgreenville/trolley-tracker-ios-client/blob/daf37bce5aa7e84b74b996003fabfcedde27c300/TrolleyTracker/Networking/URLs.swift#L90

The new url is api.trolleytracker.net

**Comment by jeremywight** [comment]
We believe that should be changed to 
http://api.yeahthattrolley.com/api

**Comment by jeremywight** [comment]
But we were unsuccessful in getting it to run and show the routes in the emulator once updated

**Comment by bikeoid** [comment]
I made a temporary test version of the server without the new fields, but still no success.

Possibly related: Trolley 1702 shows up far away today on the shores of Mole Lake, in Crandon WI!   Don't know why, but there's a trolley manufacturer in that town https://hometowntrolley.com/

**Comment by jeremywight** [comment]
We should sell them our "companion" app :D

**Comment by austin9350** [comment]
I'm looking into this now. Where is it you all aren't seeing the routes displayed?
In the AppStore app I can't test the main map view because there are no Trolleys running at the moment, but I'm seeing the routes displayed in the Schedule view.

I'm also testing in the simulator pointing to the Test server and everything seems good there.

**Comment by austin9350** [comment]
oh wait, I just downloaded the most recent TestFlight build (30) and the Schedule view doesn't show the routes. Is that the version you all were using?

**Comment by austin9350** [comment]
And I see the bug there, looks like I had started to add support for the travel times but I was looking for a key named `LastTrolleyArrivalTime` instead of `NextTrolleyArrivalTime`. I'm not sure if there was a previous iteration that used that key, or if I just made it up :-) 

Regardless, that only effects the TestFlight build, not the AppStore build. So hopefully no worries there, unless there's something else that I'm missing.

**Comment by bikeoid** [comment]
Yes, that would explain it - I am on TestFlight.  The key was renamed because I checked the source code on Github which still didn't reference the LastTrolleyArrivalTime field.

**Comment by austin9350** [comment]
Gotcha, I updated it in the branch that was using it so the next TF build should be good.

**Comment by jeremywight** [comment]
Bahh, I never considered to check if I was on the Production or TF build,
which I was... Schedule is now showing in the routes

**Comment by bikeoid** [comment]
Some trivia - the new trolleys had a design defect; some part of the chassis was overloaded.   They do need to be sent back to the manufacturer for a fix so that's why this one is in Wisconsin
